"""Stage 6: consistency checks, coverage, and the guard on provenance.

Findings are graded ERROR / WARN / INFO and written to
``docs/VALIDATION-aalam-tunisiyun.md``. ``--strict`` exits non-zero on any
ERROR, which is what CI runs.

The load-bearing check is :func:`check_quotes_are_verbatim`. Every edge claims
a sentence in the volume; this verifies that the sentence is actually there.
The multiplex build samples that check. Here it runs on **every** row, because
a model pass produced most of them and an unquotable assertion is the exact
shape a fabricated tie would take.

A check whose input is absent reports WARN naming the stage that rebuilds it,
rather than crashing or passing vacuously.
"""
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

from .llm import open_text, quote_is_verbatim
from .paths import DOCS, INTERIM, PROCESSED, RAW, load_config

_REBUILD_WITH = {
    "entry_texts.jsonl": "aalam-segment",
    "manifest.csv": "aalam-ingest",
    "entries.csv": "aalam-segment",
    "all.csv": "aalam-relations",
}


class Report:
    def __init__(self) -> None:
        self.rows: list[tuple[str, str, str]] = []

    def add(self, level: str, check: str, detail: str) -> None:
        self.rows.append((level, check, detail))

    @property
    def errors(self) -> int:
        return sum(1 for lvl, _, _ in self.rows if lvl == "ERROR")

    def render(self) -> str:
        out = ["# Validation", "",
               "Generated by `python -m aalam.validate`. Do not edit by hand.", ""]
        for level in ("ERROR", "WARN", "INFO"):
            rows = [r for r in self.rows if r[0] == level]
            if not rows:
                continue
            out += [f"## {level}", ""]
            out += [f"- **{check}** — {detail}" for _, check, detail in rows]
            out.append("")
        return "\n".join(out)


def _skip(rep: Report, check: str, needs: Path) -> None:
    stage = _REBUILD_WITH.get(needs.name, "aalam")
    rep.add("WARN", check, f"not checked: `{needs}` is absent; rebuild with `make {stage}`")


def _edges() -> list[dict]:
    path = PROCESSED / "edges" / "all.csv"
    if not path.exists():
        return []
    with open_text(path) as fh:
        return list(csv.DictReader(fh))


def check_quotes_are_verbatim(rep: Report) -> None:
    """Every edge must quote its entry. Not sampled -- all of them."""
    src = INTERIM / "entry_texts.jsonl"
    if not src.exists():
        _skip(rep, "quotes are verbatim", src)
        return
    texts = {}
    with src.open(encoding="utf-8") as fh:
        for line in fh:
            rec = json.loads(line)
            texts[rec["entry_uid"]] = rec["text"]

    edges = _edges()
    bad = [e for e in edges
           if not quote_is_verbatim(e["evidence_quote"], texts.get(e["entry_uid"], ""))]
    if bad:
        rep.add("ERROR", "quotes are verbatim",
                f"{len(bad)} of {len(edges)} edges quote text not present in their entry, "
                f"e.g. {bad[0]['edge_id']} in {bad[0]['entry_uid']}")
    else:
        rep.add("INFO", "quotes are verbatim",
                f"all {len(edges)} edges quote their entry verbatim")


def check_entries(rep: Report) -> None:
    path = PROCESSED / "entries.csv"
    if not path.exists():
        _skip(rep, "entry spine", path)
        return
    with path.open(encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))

    if len(rows) != 38:
        rep.add("ERROR", "entry count",
                f"{len(rows)} entries; the volume's contents list 38")
    else:
        rep.add("INFO", "entry count", "38 entries, matching the printed contents")

    folios = [(int(r["folio_start"]), int(r["folio_end"])) for r in rows]
    gaps = [(a[1], b[0]) for a, b in zip(folios, folios[1:]) if b[0] != a[1] + 1]
    if gaps:
        rep.add("ERROR", "entry coverage",
                f"{len(gaps)} discontinuities between entries, e.g. {gaps[0]}")
    else:
        rep.add("INFO", "entry coverage", "entries are contiguous from folio 25 to 376")

    overlaps = [(a, b) for a, b in zip(folios, folios[1:]) if b[0] <= a[1]]
    if overlaps:
        rep.add("ERROR", "entry overlap", f"{len(overlaps)} entries overlap")

    undated = [r["entry_uid"] for r in rows if not r["death_year"]]
    if undated:
        rep.add("WARN", "life dates",
                f"{len(undated)} entries without a death year: {', '.join(undated)}")
    no_birth = [r["entry_uid"] for r in rows if r["death_year"] and not r["birth_year"]]
    if no_birth:
        rep.add("INFO", "life dates",
                f"{len(no_birth)} entries state a death year but no birth year "
                f"({', '.join(no_birth)}); the volume prints '(... - YYYY)' there, "
                "so this is the source declining to say, not a parse failure")

    flagged = [r for r in rows if r["needs_review"]]
    if flagged:
        rep.add("INFO", "heading agreement",
                f"{len(flagged)} of {len(rows)} entry headings disagree with the contents "
                "list or could not be read; headings are set in display type, which OCRs "
                "poorly, and the contents list is authoritative for the name")


def check_persons(rep: Report) -> None:
    path = PROCESSED / "persons.csv"
    if not path.exists():
        _skip(rep, "person register", path)
        return
    with open_text(path) as fh:
        rows = list(csv.DictReader(fh))
    ids = [r["person_id"] for r in rows]
    if len(ids) != len(set(ids)):
        rep.add("ERROR", "person identifiers", "duplicate person_id in the register")
    unknown = [r for r in rows if r["person_id"] == "PERSON_UNKNOWN"]
    if unknown:
        rep.add("ERROR", "person identifiers",
                f"{len(unknown)} rows resolved to PERSON_UNKNOWN")
    subjects = sum(1 for r in rows if r["is_subject"] == "yes")
    rep.add("INFO", "person register",
            f"{len(rows)} persons: {subjects} subjects with an entry of their own, "
            f"{len(rows) - subjects} alters named inside one")


def check_edges(rep: Report) -> None:
    edges = _edges()
    if not edges:
        _skip(rep, "edges", PROCESSED / "edges" / "all.csv")
        return
    if any(e["from_id"] == e["to_id"] for e in edges):
        n = sum(1 for e in edges if e["from_id"] == e["to_id"])
        rep.add("ERROR", "self loops", f"{n} edges join a node to itself")
    bad_years = [
        e for e in edges
        if e["year_lo"] and e["year_hi"] and e["year_lo"] > e["year_hi"]
    ]
    if bad_years:
        rep.add("ERROR", "edge intervals",
                f"{len(bad_years)} edges have a lower bound after their upper bound")

    by_extractor = {}
    for e in edges:
        by_extractor[e["extractor"]] = by_extractor.get(e["extractor"], 0) + 1
    rep.add("INFO", "edges by extractor",
            ", ".join(f"{k}: {v}" for k, v in sorted(by_extractor.items())))

    undated = sum(1 for e in edges if e["date_precision"] in ("", "none"))
    rep.add("INFO", "edge dating",
            f"{undated} of {len(edges)} edges carry no date. A biography states a "
            "relation far more often than it dates one; an undated tie is not a tie "
            "with an unknown short duration, it is a tie the source never placed in time")


def check_ocr(rep: Report) -> None:
    path = RAW / "manifest.csv"
    if not path.exists():
        _skip(rep, "OCR coverage", path)
        return
    with path.open(encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    timeouts = [r for r in rows if r["status"] == "ocr_timeout"]
    if timeouts:
        rep.add("WARN", "OCR coverage",
                f"{len(timeouts)} page(s) abandoned on a time limit: "
                f"{', '.join('p' + r['pdf_page'] for r in timeouts)}")
    empty = sum(1 for r in rows if r["status"] == "empty")
    body = [r for r in rows if int(r["n_chars"]) > 500]
    rep.add("INFO", "OCR coverage",
            f"{len(rows)} pages, {len(body)} carrying body text, {empty} blank. "
            f"{sum(int(r['n_chars']) for r in rows):,} characters in total")
    engines = {r["ocr_version"] for r in rows}
    if len(engines) > 1:
        rep.add("WARN", "OCR provenance",
                f"pages were read by more than one engine build: {sorted(engines)}")


def check_negative_control(rep: Report) -> None:
    """Apparatus must yield nothing.

    The preface, the author's own biography and the contents list are prose
    about the book rather than about a career. If the extractor draws ties from
    them it is matching on surface patterns rather than on stated relations, so
    their silence is a genuine test and not a formality.
    """
    edges = _edges()
    if not edges:
        _skip(rep, "negative control", PROCESSED / "edges" / "all.csv")
        return
    uids = {e["entry_uid"] for e in edges}
    stray = {u for u in uids if not u.startswith("aalam:")}
    if stray:
        rep.add("ERROR", "negative control",
                f"edges drawn from outside the 38 entries: {sorted(stray)}")
    else:
        rep.add("INFO", "negative control",
                "every edge comes from one of the 38 biographies; none from the "
                "preface, the author's life, or the contents list")


def run(fail_on_error: bool = False) -> int:
    rep = Report()
    cfg = load_config("aalam_scope")
    rep.add("INFO", "scope",
            f"{cfg['volume']['title_translit']} ({cfg['volume']['pub_year']}), "
            f"subjects born {cfg['window']['start_year']}-{cfg['window']['end_year']}")
    for check in (check_ocr, check_entries, check_persons, check_edges,
                  check_quotes_are_verbatim, check_negative_control):
        check(rep)

    DOCS.mkdir(parents=True, exist_ok=True)
    (DOCS / "VALIDATION-aalam-tunisiyun.md").write_text(rep.render(), encoding="utf-8")
    print(rep.render())
    return 1 if (fail_on_error and rep.errors) else 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--strict", action="store_true", help="exit non-zero on any ERROR")
    args = ap.parse_args(argv)
    return run(fail_on_error=args.strict)


if __name__ == "__main__":
    raise SystemExit(main())
